# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21", "1.22", "1.23"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Run Tests with Coverage
      run: go test -v -coverprofile=coverage-${{ matrix.go-version }}.out ./...

    - name: Upload Coverage Artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage-${{ matrix.go-version }}.out

    - name: Display Coverage in Console
      run: go tool cover -func=coverage-${{ matrix.go-version }}.out
